name: web_ui
author: "Web UI Authors <misc@dartlang.org>"
homepage: https://github.com/dart-lang/web-ui
description: An easy way to build web apps in Dart.
version: 0.2.9
dependencies:
  args: any
  # Pin html5lib so we don't get unexpected API breaks.
  html5lib: ">=0.2.1+1 <0.2.2"
  js: any
  logging: any
  unittest: any
