name: web_components
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/dart-web-components
description: This has been renamed to web_ui. Updates will go in that package.
version: 0.2.8+5
dependencies:
  web_ui: "<0.2.9"
