name: web_components
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/dart-web-components
description: An easy way to build web apps in Dart.
version: 0.2.8+3
dependencies:
  args: any
  # Pin html5lib so we don't get unexpected API breaks.
  html5lib: ">=0.2.1+1 <0.2.2"
  js: any
  logging: any
  unittest: any
